var bankName;
console.log("before inilization bankName "+typeof bankName);
bankName="SBI Bank";
console.log("bankName datatype: "+typeof bankName);
var marks='90%';
console.log("Marks datatype: "+typeof marks);
var isWorking;
console.log("isWorking datatype before initilization: "+typeof isWorking);
isWorking=true;
console.log("isWorking datatype After initilization: "+ typeof isWorking);
var totalCount=107;
console.log("totalCount datatype: "+typeof totalCount);